### ISSUE TITLE
Ultra96 overlay status?

### ISSUE THREAD

**Issue by vegaluisjose** [yunqu/PYNQ-derivative-overlays#5]
Hi,

Great repo, do you know what is the status for Ultra96 overlay? Do you know if it is possible to re-use the one for the PYNQ and then download a basic ultra96 overlay? (say the scalar add example you guys have for the PYNQ but ported for this board).

I was trying to use what you have, but it seems that you have some hardcoded pointers to some other project [see here](https://github.com/yunqu/PYNQ-derivative-overlays/blob/master/ultra/build_ultra_system.tcl#L5-L6) for building the ultra system. I don't know how relevant is this project for the building this overlay?

Thanks!

**Comment by yunqu** [comment]
With this commit https://github.com/yunqu/PYNQ-derivative-overlays/commit/434ddbc033918b9f5504698cd8d34988330ef873, the ultra overlay (only the bitstream) is built without any dependency. So you should be able to build it now. 

For an actual overlay to run on ultra96, it is still under discussion; we will decide later on which overlay to release.
