### ISSUE TITLE
Error on loading adder.so for ultra96

### ISSUE THREAD

**Issue by mbaharan** [yunqu/PYNQ-derivative-overlays#8]
Hi,
Thanks for this great repo. I synthesized the test program for ultra96 and I uploaded `.so` file, `.hwh`, and bitstream.  In jupytor, I am able to upload the bitstream on FPGA, however when I am trying to load the `.so` by running the following section
```python
dlib = ffi.dlopen('/home/xilinx/jupyter_notebooks/sdxAdder/adder.so')
```
it shows me this error:
`OSError: cannot load library '/home/xilinx/jupyter_notebooks/sdxAdder/adder.so': libsds_lib.so: cannot open shared object file: No such file or directory.  Additionally, ctypes.util.find_library() did not manage to locate a library called '/home/xilinx/jupyter_notebooks/sdxAdder/adder.so'`,
and I am sure the `.so` file is there. I changed the content of `Ultra96/sw` with my Linux image. I am currently using Pynq v2.4.
Any help would be appreciated.

**Comment by yunqu** [comment]
There are 2 things.

1. Since we changed our libsds_lib.so to libcma.so, you may need to add the following source to compile your adder.so file:
https://github.com/sfox14/pynq-ekf/tree/master/build/src/pynqlib

2. You can follow the API here:
https://github.com/yunqu/PYNQ-derivative-overlays/blob/master/sdx_platform/README.md
Use the set_allocator_library() call

**Comment by mbaharan** [comment]
Thank a lot for the help. So I added both `pynqlib.c` and `libxlnk_cma.h` tp my project and I compiled the project. Now it gave this error:
```
OSError: cannot load library '/home/xilinx/jupyter_notebooks/sdxAdder/adder.so': /home/xilinx/jupyter_notebooks/sdxAdder/adder.so: undefined symbol: _Z19sds_alloc_cacheablej.  Additionally, ctypes.util.find_library() did not manage to locate a library called '/home/xilinx/jupyter_notebooks/sdxAdder/adder.so'
```
It seems that it couldn't find `sds_alloc_cacheable` from libcma.so. Any idea?
Thanks for the help.

**Comment by yunqu** [comment]
Can you post your notebook so I can have a look?

**Comment by mbaharan** [comment]
Sure. here it is:
```python
from pynq import Overlay, Xlnk
from pynq import Overlay, Xlnk
bs = Overlay('adder.bit')
bs.download()
Xlnk.set_allocator_library('/home/xilinx/jupyter_notebooks/sdxAdder/adder.so')
---------------------------------------------------------------------------
OSError                                   Traceback (most recent call last)
<ipython-input-7-97e4a310eff4> in <module>()
----> 1 mem_mng = Xlnk.set_allocator_library('/home/xilinx/jupyter_notebooks/sdxAdder/adder.so')

/usr/local/lib/python3.6/dist-packages/pynq/xlnk.py in set_allocator_library(cls, path)
    179 
    180         """
--> 181         cls._open_library(path)
    182         cls.libxlnk_path = path
    183 

/usr/local/lib/python3.6/dist-packages/pynq/xlnk.py in _open_library(cls, path)
    184     @classmethod
    185     def _open_library(cls, path):
--> 186         cls.libxlnk = cls.ffi.dlopen(path)
    187 
    188     def __init__(self):

/usr/lib/python3/dist-packages/cffi/api.py in dlopen(self, name, flags)
    139         assert isinstance(name, basestring) or name is None
    140         with self._lock:
--> 141             lib, function_cache = _make_ffi_library(self, name, flags)
    142             self._function_caches.append(function_cache)
    143             self._libraries.append(lib)

/usr/lib/python3/dist-packages/cffi/api.py in _make_ffi_library(ffi, libname, flags)
    800 def _make_ffi_library(ffi, libname, flags):
    801     backend = ffi._backend
--> 802     backendlib = _load_backend_lib(backend, libname, flags)
    803     #
    804     def accessor_function(name):

/usr/lib/python3/dist-packages/cffi/api.py in _load_backend_lib(backend, name, flags)
    795         if first_error is not None:
    796             msg = "%s.  Additionally, %s" % (first_error, msg)
--> 797         raise OSError(msg)
    798     return backend.load_library(path, flags)
    799 

OSError: cannot load library '/home/xilinx/jupyter_notebooks/sdxAdder/adder.so': /home/xilinx/jupyter_notebooks/sdxAdder/adder.so: undefined symbol: _Z19sds_alloc_cacheablej.  Additionally, ctypes.util.find_library() did not manage to locate a library called '/home/xilinx/jupyter_notebooks/sdxAdder/adder.so'
```

**Comment by yunqu** [comment]
Follow the example here: 
https://github.com/sfox14/pynq-ekf/blob/master/ekf/ekf.py#L50

I don't think you are using the API correctly.

**Comment by mbaharan** [comment]
Thanks for the help. I found the problem. I mistakenly used sds++ for compiling pynqlib.c.
