### ISSUE TITLE
cross-compile elf for ultra96

### ISSUE THREAD

**Issue by theDweeb** [yunqu/PYNQ-derivative-overlays#9]
Hello and thank you for this great repo.

I was hoping you could guide me on how to generate the .elf file for Ultra96 on Pynq 2.5.1 echo system? I have followed the vitis tutorials but they do not provide an official platform for Ultra96 to follow along with them: https://github.com/Xilinx/Vitis_Embedded_Platform_Source/tree/master/Xilinx_Official_Platforms

I have followed your instructions and have created the Ultra96 overlay based on the 'ultra' directory,
I then made a platform
```
make platform
```
and test
```
make test
```
I am now trying to generate the elf file on my server machine (x86, cross-compile?), or compile on the ultra96 board directly, so that I can simply
```
./host.elf 
```
and perform the vector add code

your
```
make elf
```

and

```
g++ -I$XILINX_XRT/include/ -I$XILINX_VIVADO/include/ -Wall -O0 -g -std=c++11 \
host.cpp xcl2.cpp xcl2.hpp -o 'host'  -L$XILINX_XRT/lib/ -lOpenCL -lpthread -lrt -lstdc++
```

from "Building the Software Step 4: https://github.com/Xilinx/Vitis-Tutorials/blob/master/docs/Pathway3/BuildingAnApplication.md

when compiled on the Ultra 96 allows me to do ./host vadd.xclbin but says that the platform could not be found.

I am trying to connect the dots from the vitis alveo, accel, and this tutorial to understand how to sythensize on Ultra96 on Pynq echo system.

Thanks for your help

**Comment by yunqu** [comment]
Hi, from https://github.com/yunqu/PYNQ-derivative-overlays/blob/master/vitis_platform/test/README.md you will know you can copy the test folder onto your board and compile the elf file. We did not test cross compilation so everything should be native. 

So on x86 machine, you get xclbin (hardware project); on ultra96 board, you get the executable `vadd.elf` file. And you can then run `./vadd.elf` to test it.

**Comment by theDweeb** [comment]
Thank you for your reply, I was not copying the entire test folder to the board. I have now ran into another issue:

```
XRT build version: 2.3.0
Build date: 2020-06-09
Git branch: temp
PID: 5943
UID:0
HOST: pynq
EXE: /home/xilinx/test/vadd.elf
[XRT] ERROR: XILINX_XRT must be set
Error: Failed to find Xilinx Platform
```
I have sourced vitis and xrt on host machine before following your guide. I could not find xrt on the Ultra96 board (Prebuilt Pynq 2.5.0 upgraded to 2..5.1) even though the pynq documents says it should be in /opt/xilinx/xrt

Thanks again for your help

**Comment by yunqu** [comment]
You can set XILINX_XRT to /usr:
```
export XILINX_XRT=/usr
```
Then you should be able to run.

**Comment by theDweeb** [comment]
This worked! Thank you so much!
